version: 2.1

jobs:
  build:
    machine:
      image: arm-default
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Run job_1
          command: echo "This is job_1 aaa"