version: 2.1

executors:
  small-executor:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  build_0:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_1:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_2:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_3:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_4:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_5:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_6:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_7:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_8:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_9:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_10:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_11:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_12:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_13:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_14:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_15:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_16:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_17:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_18:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_19:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_20:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_21:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_22:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_23:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_24:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_25:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_26:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_27:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_28:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_29:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_30:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_31:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_32:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_33:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_34:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_35:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_36:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_37:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_38:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_39:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_40:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_41:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_42:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_43:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_44:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_45:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_46:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_47:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_48:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_49:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_50:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_51:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_52:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_53:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_54:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_55:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_56:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_57:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_58:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_59:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_60:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_61:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_62:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_63:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_64:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_65:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_66:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_67:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_68:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_69:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_70:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_71:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_72:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_73:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_74:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_75:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_76:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_77:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_78:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_79:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_80:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_81:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_82:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_83:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_84:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_85:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_86:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_87:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_88:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_89:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_90:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_91:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_92:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_93:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_94:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_95:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_96:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_97:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_98:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"
  build_99:
    executor: small-executor
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "hello"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_0
      - build_1
      - build_2
      - build_3
      - build_4
      - build_5
      - build_6
      - build_7
      - build_8
      - build_9
      - build_10
      - build_11
      - build_12
      - build_13
      - build_14
      - build_15
      - build_16
      - build_17
      - build_18
      - build_19
      - build_20
      - build_21
      - build_22
      - build_23
      - build_24
      - build_25
      - build_26
      - build_27
      - build_28
      - build_29
      - build_30
      - build_31
      - build_32
      - build_33
      - build_34
      - build_35
      - build_36
      - build_37
      - build_38
      - build_39
      - build_40
      - build_41
      - build_42
      - build_43
      - build_44
      - build_45
      - build_46
      - build_47
      - build_48
      - build_49
      - build_50
      - build_51
      - build_52
      - build_53
      - build_54
      - build_55
      - build_56
      - build_57
      - build_58
      - build_59
      - build_60
      - build_61
      - build_62
      - build_63
      - build_64
      - build_65
      - build_66
      - build_67
      - build_68
      - build_69
      - build_70
      - build_71
      - build_72
      - build_73
      - build_74
      - build_75
      - build_76
      - build_77
      - build_78
      - build_79
      - build_80
      - build_81
      - build_82
      - build_83
      - build_84
      - build_85
      - build_86
      - build_87
      - build_88
      - build_89
      - build_90
      - build_91
      - build_92
      - build_93
      - build_94
      - build_95
      - build_96
      - build_97
      - build_98
      - build_99
